sources:
  - name: github_data
    schema: raws
    description: "Données brutes de GitHub importées depuis les fichiers Parquet"
    tables:
      - name: forks_data
        description: "Données brutes des forks"
      - name: issues_data
        description: "Données brutes des issues"
      - name: contributors_data
        description: "Données brutes des contributeurs"
      - name: suscribers_data
        description: "Données brutes des abonnés"
      - name: stargazers_data
        d escription: "Données brutes des étoiles"